Repository AY2223S1-CS2103T-T12-1/tp, pull requests merged in 2022-09, with the labels that each got.

#39 Add periods to sentences and shorten reposense link
  docs/team/njxue.md
Labels: documentation

#43 DG: Update Scope, NFR, Glossary
  docs/DeveloperGuide.md
Labels: documentation

#47 Add more user stories
  docs/DeveloperGuide.md
Labels: documentation, priority.HIGH

#52 Refactor use cases to include inclusions and more extensions
  docs/DeveloperGuide.md
Labels: documentation, priority.MEDIUM
