Repository AY2223S1-CS2103T-T12-1/tp, pull requests merged in 2022-11, with the labels that each got.

#326 Add `ViewCommand` tests
  src/test/java/seedu/taassist/logic/commands/ViewCommandTest.java
Labels: priority.MEDIUM, tests

#327 Add `GradeCommand` tests
  src/main/java/seedu/taassist/commons/core/Messages.java
  src/main/java/seedu/taassist/model/moduleclass/StudentModuleData.java
  src/main/java/seedu/taassist/model/session/SessionData.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/test/java/seedu/taassist/logic/commands/GradeCommandTest.java
  src/test/java/seedu/taassist/model/moduleclass/StudentModuleDataTest.java
  src/test/java/seedu/taassist/model/student/StudentTest.java
Labels: priority.MEDIUM, tests

#321 Fix class names mismatch between command result and remaining parts of GUI
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/index.md
  src/main/java/seedu/taassist/logic/commands/AddcCommand.java
  src/main/java/seedu/taassist/logic/commands/AddsCommand.java
  src/main/java/seedu/taassist/logic/commands/AssignCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/main/java/seedu/taassist/logic/commands/FocusCommand.java
  src/main/java/seedu/taassist/logic/commands/ScoresCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
  src/main/java/seedu/taassist/logic/commands/ViewCommand.java
  src/main/java/seedu/taassist/logic/parser/AddcCommandParser.java
  src/main/java/seedu/taassist/logic/parser/AddsCommandParser.java
  src/main/java/seedu/taassist/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/taassist/logic/parser/DeletecCommandParser.java
  src/main/java/seedu/taassist/logic/parser/DeletesCommandParser.java
  src/main/java/seedu/taassist/model/Model.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/test/java/seedu/taassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
  src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
  src/test/java/seedu/taassist/logic/commands/DeletecCommandTest.java
  src/test/java/seedu/taassist/logic/commands/FocusCommandTest.java
  src/test/java/seedu/taassist/logic/commands/ScoresCommandTest.java
  src/test/java/seedu/taassist/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/taassist/logic/commands/UnfocusCommandTest.java
  src/test/java/seedu/taassist/logic/commands/ViewCommandTest.java
  src/test/java/seedu/taassist/model/stubs/ModelStub.java
  src/test/java/seedu/taassist/model/stubs/ModelStubInFocusMode.java
  src/test/java/seedu/taassist/model/stubs/ModelStubWithNoModuleClass.java
Labels: type.Bug, severity.Medium

#328 UGDG Update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddsCommandSequenceDiagram.puml
  docs/diagrams/AssignCommandSequenceDiagram.puml
  docs/diagrams/FocusCommandSequenceDiagram.puml
  docs/diagrams/GradeCommandSequenceDiagram.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/diagrams/XYZCommandParserSequenceDiagram.puml
  docs/images/AddsCommandSequenceDiagram.png
  docs/images/AssignCommandSequenceDiagram.png
  docs/images/FocusCommandSequenceDiagram.png
  docs/images/GradeCommandSequenceDiagram.png
  docs/images/ViewCommandSequenceDiagram.png
  docs/images/XYZCommandParserSequenceDiagram.png
  src/main/java/seedu/taassist/model/TaAssist.java
Labels: documentation, priority.MEDIUM, type.Chore

#323 Fix UG and DG inconsistencies, grammar issues and minor bug fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UiFocusScreen.png
  docs/images/UiGrading.png
  docs/images/UiMainScreen.png
  docs/team/optionalemon.md
  src/main/resources/view/DarkTheme.css
Labels: documentation, priority.LOW

#329 Add tests: `StudentView`, `MappedStudentViewList`, and `AddsCommand`
  src/main/java/seedu/taassist/model/student/StudentView.java
  src/test/java/seedu/taassist/logic/commands/AddsCommandTest.java
  src/test/java/seedu/taassist/model/student/MappedStudentViewListTest.java
  src/test/java/seedu/taassist/model/student/StudentViewTest.java
Labels: priority.MEDIUM, type.Chore, tests

#333 Put constraints on class length
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
Labels: type.Bug

#338 Change all instances of 'TA Assist' to 'TA-Assist'
  README.md
  docs/DeveloperGuide.md
  docs/team/berted.md
  docs/team/bubbl3t.md
  docs/team/njxue.md
  docs/team/optionalemon.md
  docs/team/rezwanarefin01.md
  src/main/resources/view/MainWindow.fxml
Labels: documentation, priority.LOW

#335 Change grade Label to a Text
  docs/team/rezwanarefin01.md
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/main/java/seedu/taassist/ui/ModuleClassCard.java
  src/main/java/seedu/taassist/ui/SessionCard.java
  src/main/java/seedu/taassist/ui/StudentCard.java
  src/main/java/seedu/taassist/ui/StudentCardTitle.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ModuleClassCard.fxml
  src/main/resources/view/SessionCard.fxml
  src/main/resources/view/StudentCard.fxml
  src/main/resources/view/StudentCardTitle.fxml
Labels: type.Bug, enhancement

#337 Fix session names mismatch between command messages and GUI
  src/main/java/seedu/taassist/logic/commands/AddsCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/ScoresCommand.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/moduleclass/exceptions/SessionNotFoundException.java
Labels: type.Bug, severity.Medium

#341 Polymorph UI and storage actions for better abstraction
  src/main/java/seedu/taassist/commons/core/csv/CsvConfig.java
  src/main/java/seedu/taassist/logic/LogicManager.java
  src/main/java/seedu/taassist/logic/commands/ClearCommand.java
  src/main/java/seedu/taassist/logic/commands/CommandResult.java
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/main/java/seedu/taassist/logic/commands/ExitCommand.java
  src/main/java/seedu/taassist/logic/commands/ExportCommand.java
  src/main/java/seedu/taassist/logic/commands/FocusCommand.java
  src/main/java/seedu/taassist/logic/commands/HelpCommand.java
  src/main/java/seedu/taassist/logic/commands/UnfocusCommand.java
  src/main/java/seedu/taassist/logic/commands/actions/ExportCsvStorageAction.java
  src/main/java/seedu/taassist/logic/commands/actions/StorageAction.java
  src/main/java/seedu/taassist/logic/commands/actions/UiAction.java
  src/main/java/seedu/taassist/storage/Storage.java
  src/main/java/seedu/taassist/storage/StorageManager.java
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/test/java/seedu/taassist/logic/commands/ClearCommandTest.java
  src/test/java/seedu/taassist/logic/commands/CommandResultTest.java
  src/test/java/seedu/taassist/logic/commands/ExitCommandTest.java
  src/test/java/seedu/taassist/logic/commands/HelpCommandTest.java
Labels: priority.MEDIUM

#340 UG: Adds Parameter Constraints
  docs/UserGuide.md
  docs/team/berted.md
Labels: documentation, priority.MEDIUM

#346 Fix data loading bugs and improve storage tests
  docs/UserGuide.md
  docs/team/rezwanarefin01.md
  src/main/java/seedu/taassist/MainApp.java
  src/main/java/seedu/taassist/logic/commands/EditCommand.java
  src/main/java/seedu/taassist/logic/commands/ExportCommand.java
  src/main/java/seedu/taassist/logic/commands/FindCommand.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/ListCommand.java
  src/main/java/seedu/taassist/logic/commands/ViewCommand.java
  src/main/java/seedu/taassist/logic/parser/AddCommandParser.java
  src/main/java/seedu/taassist/logic/parser/FindCommandParser.java
  src/main/java/seedu/taassist/logic/parser/GradeCommandParser.java
  src/main/java/seedu/taassist/logic/parser/ParserUtil.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/session/Date.java
  src/main/java/seedu/taassist/model/student/SessionData.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/main/java/seedu/taassist/model/student/StudentModuleData.java
  src/main/java/seedu/taassist/model/student/StudentView.java
  src/main/java/seedu/taassist/model/student/predicate/IsPartOfClassPredicate.java
  src/main/java/seedu/taassist/model/student/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/taassist/model/util/SampleDataUtil.java
  src/main/java/seedu/taassist/storage/JsonAdaptedModuleClass.java
  src/main/java/seedu/taassist/storage/JsonAdaptedSession.java
  src/main/java/seedu/taassist/storage/JsonAdaptedSessionData.java
  src/main/java/seedu/taassist/storage/JsonAdaptedStudent.java
  src/main/java/seedu/taassist/storage/JsonAdaptedStudentModuleData.java
  src/main/java/seedu/taassist/storage/JsonSerializableTaAssist.java
  src/main/java/seedu/taassist/storage/Storage.java
  src/main/java/seedu/taassist/storage/StorageManager.java
  src/main/java/seedu/taassist/ui/StudentCard.java
  src/test/data/JsonSerializableTaAssistTest/duplicateModuleClassTaAssist.json
  src/test/data/JsonSerializableTaAssistTest/nonExistentModuleTaAssist.json
  src/test/data/JsonSerializableTaAssistTest/nonExistentSessionTaAssist.json
  src/test/data/JsonSerializableTaAssistTest/typicalStudentsTaAssist.json
  src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
  src/test/java/seedu/taassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taassist/logic/commands/FindCommandTest.java
  src/test/java/seedu/taassist/logic/commands/GradeCommandTest.java
  src/test/java/seedu/taassist/logic/commands/ViewCommandTest.java
  src/test/java/seedu/taassist/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/taassist/logic/parser/GradeCommandParserTest.java
  src/test/java/seedu/taassist/logic/parser/TaAssistParserTest.java
  src/test/java/seedu/taassist/model/ModelManagerTest.java
  src/test/java/seedu/taassist/model/student/StudentModuleDataTest.java
  src/test/java/seedu/taassist/model/student/StudentTest.java
  src/test/java/seedu/taassist/model/student/StudentViewTest.java
  src/test/java/seedu/taassist/model/student/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedModuleClassTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedSessionDataTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedSessionTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedStudentModuleDataTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/taassist/storage/JsonSerializableTaAssistTest.java
  src/test/java/seedu/taassist/storage/StorageManagerTest.java
  src/test/java/seedu/taassist/testutil/StudentBuilder.java
  src/test/java/seedu/taassist/testutil/TypicalModuleClasses.java
  src/test/java/seedu/taassist/testutil/TypicalSessions.java
  src/test/java/seedu/taassist/testutil/TypicalStudents.java
Labels: type.Bug, priority.HIGH, tests

#342 Make collection of Sessions to be UniqueList
  docs/UserGuide.md
  docs/team/njxue.md
  src/main/java/seedu/taassist/logic/commands/AddsCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/test/java/seedu/taassist/logic/commands/AddsCommandTest.java
  src/test/java/seedu/taassist/model/moduleclass/ModuleClassTest.java
Labels: priority.MEDIUM

#336 Update Sessions::compareTo to sort in reverse chronological order
  src/main/java/seedu/taassist/model/session/Session.java
  src/main/java/seedu/taassist/model/uniquelist/UniqueList.java
Labels: type.Bug, priority.HIGH

#354 DG: loading and saving details, styling, consistency changes
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/_sass/minima/_base.scss
  docs/_sass/minima/initialize.scss
  docs/assets/css/style.scss
  docs/team/rezwanarefin01.md
Labels: documentation, priority.HIGH

#357 Improve code quality of `JsonSerializableTaAssist#toModelType`
  src/main/java/seedu/taassist/storage/JsonSerializableTaAssist.java
Labels: type.Chore

#356 Refactor `ParserStudentIndexUtil` to `IndexUtil`
  docs/DeveloperGuide.md
  docs/assets/css/style.scss
  docs/diagrams/GradeCommandSequenceDiagram.puml
  docs/diagrams/StudentGradeUpdate.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/GradeCommandSequenceDiagram.png
  docs/images/StudentGradeUpdate.png
  docs/images/ViewCommandSequenceDiagram.png
  src/main/java/seedu/taassist/commons/core/index/IndexUtil.java
  src/main/java/seedu/taassist/logic/commands/AssignCommand.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
  src/main/java/seedu/taassist/logic/commands/ViewCommand.java
  src/main/java/seedu/taassist/logic/parser/ParserStudentIndexUtil.java
Labels: priority.MEDIUM

#352 Make module class names all uppercased and session names all capitalised
  docs/UserGuide.md
  docs/images/sampleFocusedGui.png
  docs/images/sampleScoresGui.png
  docs/images/scoresAssignment1Result.png
  docs/team/njxue.md
  src/main/java/seedu/taassist/commons/core/Messages.java
  src/main/java/seedu/taassist/commons/util/StringUtil.java
  src/main/java/seedu/taassist/logic/commands/AddCommand.java
  src/main/java/seedu/taassist/logic/commands/AddcCommand.java
  src/main/java/seedu/taassist/logic/commands/AddsCommand.java
  src/main/java/seedu/taassist/logic/commands/AssignCommand.java
  src/main/java/seedu/taassist/logic/commands/CommandUtil.java
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/main/java/seedu/taassist/logic/commands/ExportCommand.java
  src/main/java/seedu/taassist/logic/commands/FocusCommand.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/ScoresCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
  src/main/java/seedu/taassist/logic/commands/UnfocusCommand.java
  src/main/java/seedu/taassist/logic/commands/ViewCommand.java
  src/main/java/seedu/taassist/model/Model.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/moduleclass/exceptions/SessionNotFoundException.java
  src/main/java/seedu/taassist/model/session/Session.java
  src/test/java/seedu/taassist/commons/util/StringUtilTest.java
  src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
  src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
  src/test/java/seedu/taassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taassist/logic/commands/DeletecCommandTest.java
  src/test/java/seedu/taassist/logic/commands/DeletesCommandTest.java
  src/test/java/seedu/taassist/logic/commands/FocusCommandTest.java
  src/test/java/seedu/taassist/logic/commands/GradeCommandTest.java
  src/test/java/seedu/taassist/logic/commands/ScoresCommandTest.java
  src/test/java/seedu/taassist/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/taassist/model/moduleclass/ModuleClassTest.java
  src/test/java/seedu/taassist/model/session/SessionTest.java
  src/test/java/seedu/taassist/model/stubs/ModelStub.java
  src/test/java/seedu/taassist/model/stubs/ModelStubWithNoModuleClass.java
  src/test/java/seedu/taassist/testutil/ModuleClassBuilder.java
  src/test/java/seedu/taassist/testutil/SessionBuilder.java
Labels: priority.MEDIUM, type.Chore

#361 Fix corrupt datafile getting backed up
  docs/team/rezwanarefin01.md
  src/main/java/seedu/taassist/MainApp.java
Labels: type.Bug

#362 UG: Add Description on Auto-backup
  docs/UserGuide.md
Labels: documentation, priority.MEDIUM, type.Chore

#363 Update PPP
  docs/team/optionalemon.md
Labels: documentation, priority.MEDIUM, type.Chore

#360 `MappedStudentViewList`: Add Javadoc comments
  src/main/java/seedu/taassist/model/student/MappedStudentViewList.java
Labels: documentation, priority.MEDIUM, type.Chore

#371 Fix ug dg images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiFocusScreen.png
  docs/images/UiGrading.png
  docs/images/UiMainScreen.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/sampleFocusedGui.png
  docs/images/sampleGui.png
  docs/images/sampleScoresGui.png
  docs/team/optionalemon.md
Labels: documentation

#370 Add implementation of ExportCommand to DG
  docs/DeveloperGuide.md
  docs/diagrams/ExportCommandSequenceDiagram.puml
  docs/images/ExportCommandSequenceDiagram.png
  docs/team/bubbl3t.md
Labels: documentation

#369 Add tests for `getCommandMessage` and `CommandUtil`
  docs/UserGuide.md
  docs/team/njxue.md
  src/main/java/seedu/taassist/logic/commands/CommandUtil.java
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
  src/test/java/seedu/taassist/logic/commands/AddsCommandTest.java
  src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
  src/test/java/seedu/taassist/logic/commands/CommandUtilTest.java
  src/test/java/seedu/taassist/logic/commands/DeletecCommandTest.java
  src/test/java/seedu/taassist/logic/commands/DeletesCommandTest.java
  src/test/java/seedu/taassist/logic/commands/GradeCommandTest.java
  src/test/java/seedu/taassist/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/taassist/model/stubs/ModelStubAcceptingModuleClasses.java
Labels: tests

#374 UGDG: Grammar Fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/berted.md
  src/main/resources/view/StudentCardTitle.fxml
Labels: documentation, priority.MEDIUM, type.Chore
