Repository AY2223S1-CS2103T-T12-1/tp, pull requests merged in 2022-10, with the labels that each got.

#66 Add `class` command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClassCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClassCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/IsPartOfClassPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.HIGH

#75 Exit focus mode with `back` and fix `list` command
  src/main/java/seedu/taassist/commons/core/Messages.java
  src/main/java/seedu/taassist/logic/commands/BackCommand.java
  src/main/java/seedu/taassist/logic/commands/ClassCommand.java
  src/main/java/seedu/taassist/logic/commands/ListCommand.java
  src/main/java/seedu/taassist/logic/parser/TaAssistParser.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/test/java/seedu/taassist/logic/LogicManagerTest.java
  src/test/java/seedu/taassist/logic/commands/ListCommandTest.java
Labels: type.Bug, type.Story

#98 Fix bug with class command
  src/main/java/seedu/taassist/logic/parser/ClassCommandParser.java
Labels: type.Bug

#108 Add toString method to Index
  src/main/java/seedu/taassist/commons/core/index/Index.java
Labels: type.Bug

#102 Fix deletec command
  src/main/java/seedu/taassist/commons/core/Messages.java
  src/main/java/seedu/taassist/logic/commands/AssignCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
  src/main/java/seedu/taassist/logic/parser/AddCommandParser.java
  src/main/java/seedu/taassist/logic/parser/AddcCommandParser.java
  src/main/java/seedu/taassist/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/taassist/logic/parser/AssignCommandParser.java
  src/main/java/seedu/taassist/logic/parser/DeletecCommandParser.java
  src/main/java/seedu/taassist/logic/parser/UnassignCommandParser.java
  src/main/java/seedu/taassist/model/Model.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/test/java/seedu/taassist/logic/commands/AddCommandTest.java
Labels: type.Bug

#119 Update the DG with current implementation of `TA Assist`
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/AssignCommandSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FocusCommandSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/AssignCommandSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FocusCommandSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#128 Add tests for FocusCommand and BackCommand
  src/test/java/seedu/taassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/taassist/logic/commands/BackCommandTest.java
  src/test/java/seedu/taassist/logic/commands/FocusCommandTest.java
  src/test/java/seedu/taassist/model/ModelStub.java
Labels: tests

#130 Extract generic UniqueList class from existing Unique*List classes
  src/main/java/seedu/taassist/logic/commands/EditCommand.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/moduleclass/UniqueModuleClassList.java
  src/main/java/seedu/taassist/model/student/IsPartOfClassPredicate.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/main/java/seedu/taassist/model/student/UniqueStudentList.java
  src/main/java/seedu/taassist/model/student/exceptions/DuplicateStudentException.java
  src/main/java/seedu/taassist/model/student/exceptions/StudentNotFoundException.java
  src/main/java/seedu/taassist/model/uniquelist/Identity.java
  src/main/java/seedu/taassist/model/uniquelist/UniqueList.java
  src/main/java/seedu/taassist/model/uniquelist/exceptions/DuplicateElementException.java
  src/main/java/seedu/taassist/model/uniquelist/exceptions/ElementNotFoundException.java
  src/test/java/seedu/taassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/taassist/logic/commands/FocusCommandTest.java
  src/test/java/seedu/taassist/model/TaAssistTest.java
  src/test/java/seedu/taassist/model/student/StudentTest.java
  src/test/java/seedu/taassist/model/student/UniqueStudentListTest.java
  src/test/java/seedu/taassist/model/uniquelist/UniqueListTest.java
Labels: enhancement

#132 Refactor BackCommand to UnfocusCommand
  docs/UserGuide.md
  src/main/java/seedu/taassist/logic/commands/UnfocusCommand.java
  src/main/java/seedu/taassist/logic/parser/TaAssistParser.java
  src/test/java/seedu/taassist/logic/commands/FocusCommandTest.java
  src/test/java/seedu/taassist/logic/commands/UnfocusCommandTest.java
Labels: type.Chore

#129 Add tests for module classes and addc command
  src/main/java/seedu/taassist/logic/commands/AddcCommand.java
  src/main/java/seedu/taassist/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableTaAssistTest/duplicateStudentTaAssist.json
  src/test/data/JsonSerializableTaAssistTest/invalidStudentTaAssist.json
  src/test/data/JsonSerializableTaAssistTest/typicalStudentsTaAssist.json
  src/test/java/seedu/taassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
  src/test/java/seedu/taassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taassist/logic/commands/EditCommandTest.java
  src/test/java/seedu/taassist/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/taassist/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/taassist/logic/parser/AddcCommandParserTest.java
  src/test/java/seedu/taassist/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/taassist/model/ModelStub.java
  src/test/java/seedu/taassist/model/TaAssistTest.java
  src/test/java/seedu/taassist/model/moduleclass/ModuleClassTest.java
  src/test/java/seedu/taassist/model/session/SessionTest.java
  src/test/java/seedu/taassist/model/student/StudentTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/taassist/testutil/ModuleClassBuilder.java
  src/test/java/seedu/taassist/testutil/TypicalModuleClasses.java
  src/test/java/seedu/taassist/testutil/TypicalSessions.java
  src/test/java/seedu/taassist/testutil/TypicalStudents.java
Labels: tests

#139 Add the deletes command to delete sessions
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/main/java/seedu/taassist/logic/parser/DeletesCommandParser.java
  src/main/java/seedu/taassist/logic/parser/ParserUtil.java
  src/main/java/seedu/taassist/logic/parser/SessionCommandParser.java
  src/main/java/seedu/taassist/logic/parser/TaAssistParser.java
Labels: type.Story, severity.High

#141 Update addc to add multiple classes and user guide
  docs/UserGuide.md
  src/main/java/seedu/taassist/logic/commands/AddcCommand.java
  src/main/java/seedu/taassist/logic/parser/AddcCommandParser.java
  src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
  src/test/java/seedu/taassist/logic/parser/AddcCommandParserTest.java
Labels: type.Bug, priority.MEDIUM

#148 Add `grade` and `view` commands
  src/main/java/seedu/taassist/logic/commands/AssignCommand.java
  src/main/java/seedu/taassist/logic/commands/EditCommand.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
  src/main/java/seedu/taassist/logic/commands/ViewCommand.java
  src/main/java/seedu/taassist/logic/parser/AddCommandParser.java
  src/main/java/seedu/taassist/logic/parser/CliSyntax.java
  src/main/java/seedu/taassist/logic/parser/EditCommandParser.java
  src/main/java/seedu/taassist/logic/parser/GradeCommandParser.java
  src/main/java/seedu/taassist/logic/parser/ParserStudentIndexUtil.java
  src/main/java/seedu/taassist/logic/parser/TaAssistParser.java
  src/main/java/seedu/taassist/logic/parser/ViewCommandParser.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/moduleclass/StudentModuleData.java
  src/main/java/seedu/taassist/model/session/Session.java
  src/main/java/seedu/taassist/model/session/SessionData.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/main/java/seedu/taassist/model/util/SampleDataUtil.java
  src/main/java/seedu/taassist/storage/JsonAdaptedSessionData.java
  src/main/java/seedu/taassist/storage/JsonAdaptedStudent.java
  src/main/java/seedu/taassist/storage/JsonAdaptedStudentModuleData.java
  src/main/java/seedu/taassist/storage/JsonSerializableTaAssist.java
  src/test/data/JsonSerializableTaAssistTest/duplicateStudentTaAssist.json
  src/test/data/JsonSerializableTaAssistTest/typicalStudentsTaAssist.json
  src/test/java/seedu/taassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taassist/logic/commands/EditCommandTest.java
  src/test/java/seedu/taassist/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/taassist/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/taassist/model/session/SessionTest.java
  src/test/java/seedu/taassist/model/student/StudentTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/taassist/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/taassist/testutil/StudentBuilder.java
  src/test/java/seedu/taassist/testutil/StudentUtil.java
  src/test/java/seedu/taassist/testutil/TypicalStudents.java
Labels: type.Story, priority.HIGH

#137 Fix bug in deleting classes from TA Assist
  src/main/java/seedu/taassist/logic/commands/AddcCommand.java
  src/main/java/seedu/taassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/main/java/seedu/taassist/logic/commands/EditCommand.java
  src/main/java/seedu/taassist/logic/commands/FindCommand.java
  src/main/java/seedu/taassist/logic/commands/FocusCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
Labels: type.Bug

#144 Session: Add Date field
  src/main/java/seedu/taassist/logic/commands/SessionCommand.java
  src/main/java/seedu/taassist/logic/parser/CliSyntax.java
  src/main/java/seedu/taassist/logic/parser/ParserUtil.java
  src/main/java/seedu/taassist/logic/parser/SessionCommandParser.java
  src/main/java/seedu/taassist/model/session/Date.java
  src/main/java/seedu/taassist/model/session/Session.java
  src/main/java/seedu/taassist/storage/JsonAdaptedSession.java
  src/test/java/seedu/taassist/model/session/SessionTest.java
  src/test/java/seedu/taassist/testutil/ModuleClassBuilder.java
  src/test/java/seedu/taassist/testutil/SessionBuilder.java
  src/test/java/seedu/taassist/testutil/TypicalModuleClasses.java
  src/test/java/seedu/taassist/testutil/TypicalSessions.java
Labels: priority.MEDIUM

#145 Add test for json adapted module class
  src/main/java/seedu/taassist/storage/JsonAdaptedModuleClass.java
  src/test/java/seedu/taassist/logic/commands/SessionCommandTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedModuleClassTest.java
Labels: priority.MEDIUM, tests

#162 Add tests for `JsonAdaptedSession`
  src/main/java/seedu/taassist/storage/JsonAdaptedSession.java
  src/test/java/seedu/taassist/storage/JsonAdaptedSessionTest.java
Labels: priority.MEDIUM, type.Chore

#175 Command: Fix presentation bugs
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/ViewCommand.java
Labels: type.Bug, priority.MEDIUM

#158 Update DG with new model
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/AssignCommandSequenceDiagram.puml
  docs/diagrams/FocusCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StudentAndModuleClassDiagram.puml
  docs/diagrams/TaAssistObjectDiagram.puml
  docs/diagrams/style.puml
  docs/images/AssignCommandSequenceDiagram.png
  docs/images/FocusCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StudentAndModuleClassDiagram.png
  docs/images/TaAssistObjectDiagram.png
Labels: documentation

#176 Add implementation of class related features to DG
  docs/DeveloperGuide.md
  docs/index.md
  docs/team/bubbl3t.md
Labels: documentation, priority.HIGH

#131 Add test cases for AssignCommand and UnassignCommand
  src/main/java/seedu/taassist/model/util/SampleDataUtil.java
  src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
  src/test/java/seedu/taassist/logic/commands/DeletecCommandTest.java
  src/test/java/seedu/taassist/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/taassist/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/taassist/model/TaAssistTest.java
  src/test/java/seedu/taassist/model/student/StudentTest.java
  src/test/java/seedu/taassist/storage/JsonSerializableTaAssistTest.java
  src/test/java/seedu/taassist/testutil/StudentBuilder.java
  src/test/java/seedu/taassist/testutil/TypicalModuleClasses.java
  src/test/java/seedu/taassist/testutil/TypicalSessions.java
  src/test/java/seedu/taassist/testutil/TypicalStudents.java
Labels: tests

#179 DG: Added Acknowledgements and Implementation Details
  docs/DeveloperGuide.md
  docs/diagrams/FocusCommandSequenceDiagram.puml
  docs/diagrams/ImpleIdentityObjectDiagram.puml
  docs/diagrams/ImpleIdentityObjectDiagram2.puml
  docs/diagrams/SessionCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ImpleIdentityObjectDiagram.png
  docs/images/ImpleIdentityObjectDiagram2.png
  docs/images/SessionCommandSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/berted.md
Labels: documentation, priority.MEDIUM, type.Chore

#180 Add GradeCommand implementation details to DG
  docs/DeveloperGuide.md
  docs/diagrams/GradeCommandSequenceDiagram.puml
  docs/images/GradeCommandSequenceDiagram.png
Labels: documentation

#181 Update DG on UI details and PPP on contributions
  docs/DeveloperGuide.md
  docs/team/optionalemon.md
Labels: documentation

#183 Add ViewCommand implementation details to DG
  docs/DeveloperGuide.md
  docs/diagrams/GradeCommandSequenceDiagram.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/GradeCommandSequenceDiagram.png
  docs/images/ViewCommandSequenceDiagram.png
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
Labels: documentation

#207 Fix delete session command and refactor updating of immutable classes
  src/main/java/seedu/taassist/logic/commands/AssignCommand.java
  src/main/java/seedu/taassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/SessionCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
  src/main/java/seedu/taassist/model/Model.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/moduleclass/StudentModuleData.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/test/java/seedu/taassist/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/taassist/logic/commands/DeletecCommandTest.java
  src/test/java/seedu/taassist/model/ModelStub.java
  src/test/java/seedu/taassist/storage/JsonSerializableTaAssistTest.java
Labels: type.Bug, severity.High

#204 Alert user on data load fail
  docs/team/rezwanarefin01.md
  src/main/java/seedu/taassist/MainApp.java
Labels: enhancement

#206 DG: Update leftover JsonAdapted* classes
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/taassist/model/student/Student.java
Labels: documentation

#199 Implement Command box and help bar UI
  docs/UserGuide.md
  src/main/java/seedu/taassist/logic/Logic.java
  src/main/java/seedu/taassist/logic/LogicManager.java
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/main/java/seedu/taassist/ui/ModuleClassCard.java
  src/main/java/seedu/taassist/ui/ModuleClassListPanel.java
  src/main/java/seedu/taassist/ui/UiManager.java
  src/main/resources/images/redirect_icon.png
  src/main/resources/images/ta_assist_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleClassListCard.fxml
  src/main/resources/view/ModuleClassListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/taassist/commons/util/AppUtilTest.java
Labels: priority.HIGH

#203 DG: Update grade command implementation for multiple grading
  docs/DeveloperGuide.md
  docs/diagrams/GradeCommandSequenceDiagram.puml
  docs/images/GradeCommandSequenceDiagram.png
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
Labels: documentation

#208 Fix inconsistency in commands
  docs/UserGuide.md
  src/main/java/seedu/taassist/logic/commands/AddCommand.java
  src/main/java/seedu/taassist/logic/commands/AddcCommand.java
  src/main/java/seedu/taassist/logic/commands/AssignCommand.java
  src/main/java/seedu/taassist/logic/commands/Command.java
  src/main/java/seedu/taassist/logic/commands/EditCommand.java
  src/main/java/seedu/taassist/logic/commands/FindCommand.java
  src/main/java/seedu/taassist/logic/commands/UnassignCommand.java
  src/main/java/seedu/taassist/logic/parser/EditCommandParser.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/test/java/seedu/taassist/logic/parser/EditCommandParserTest.java
Labels: documentation, priority.LOW, type.Chore

#200 Add `scores` command to show student scores of a specific session on query.
  docs/UserGuide.md
  docs/images/scoresAssignment1Result.PNG
  src/main/java/seedu/taassist/commons/core/Messages.java
  src/main/java/seedu/taassist/logic/Logic.java
  src/main/java/seedu/taassist/logic/LogicManager.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/logic/commands/ScoresCommand.java
  src/main/java/seedu/taassist/logic/commands/ViewCommand.java
  src/main/java/seedu/taassist/logic/parser/ScoresCommandParser.java
  src/main/java/seedu/taassist/logic/parser/TaAssistParser.java
  src/main/java/seedu/taassist/model/Model.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/main/java/seedu/taassist/model/moduleclass/StudentModuleData.java
  src/main/java/seedu/taassist/model/student/MappedStudentViewList.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/main/java/seedu/taassist/model/student/StudentView.java
  src/main/java/seedu/taassist/model/uniquelist/UniqueList.java
  src/main/java/seedu/taassist/storage/JsonSerializableTaAssist.java
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/main/java/seedu/taassist/ui/StudentCard.java
  src/main/java/seedu/taassist/ui/StudentListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/taassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taassist/logic/commands/ScoresCommandTest.java
  src/test/java/seedu/taassist/logic/parser/ScoresCommandParserTest.java
  src/test/java/seedu/taassist/model/ModelStub.java
  src/test/java/seedu/taassist/model/uniquelist/UniqueListTest.java
Labels: priority.HIGH, type.Enhancement

#215 Create a backup of data file everytime TA-Assist is run
  docs/team/rezwanarefin01.md
  src/main/java/seedu/taassist/MainApp.java
  src/main/java/seedu/taassist/storage/Storage.java
  src/main/java/seedu/taassist/storage/StorageManager.java
Labels: enhancement

#223 Wrap result display
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement

#225 Make sessions and classes case insensitive
  docs/team/bubbl3t.md
  src/main/java/seedu/taassist/commons/util/StringUtil.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/session/Session.java
  src/test/java/seedu/taassist/commons/util/StringUtilTest.java
Labels: type.Bug, enhancement, type.Chore, severity.Medium

#238 Fix UI button not exiting focus mode bug
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#224 Fix inconsistency between `addc` and `deletec` commands.
  src/main/java/seedu/taassist/logic/commands/AddcCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/main/java/seedu/taassist/logic/commands/DeletesCommand.java
  src/main/java/seedu/taassist/model/Model.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
  src/test/java/seedu/taassist/logic/commands/DeletecCommandTest.java
  src/test/java/seedu/taassist/model/ModelStub.java
Labels: type.Bug, enhancement, priority.MEDIUM

#240 Add session date to the session card
  src/main/java/seedu/taassist/ui/SessionCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SessionListCard.fxml
Labels: priority.HIGH, type.Enhancement

#249 Fix `export` command
  src/main/java/seedu/taassist/model/session/Session.java
  src/test/java/seedu/taassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taassist/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/taassist/logic/parser/SessionCommandParserTest.java
  src/test/java/seedu/taassist/model/session/SessionTest.java
  src/test/java/seedu/taassist/storage/JsonAdaptedSessionTest.java
Labels: type.Bug, severity.High

#231 Sort SessionData according to the date of the Session
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/main/java/seedu/taassist/model/moduleclass/ModuleClass.java
  src/main/java/seedu/taassist/model/moduleclass/StudentModuleData.java
  src/main/java/seedu/taassist/model/session/Session.java
  src/main/java/seedu/taassist/model/session/SessionData.java
  src/main/java/seedu/taassist/model/student/Student.java
  src/main/java/seedu/taassist/model/uniquelist/UniqueList.java
  src/test/java/seedu/taassist/model/uniquelist/UniqueListTest.java
Labels: enhancement, priority.MEDIUM

#253 Allow session command to accept multiple sessions
  docs/UserGuide.md
  src/main/java/seedu/taassist/logic/commands/SessionCommand.java
  src/main/java/seedu/taassist/logic/parser/ParserUtil.java
  src/main/java/seedu/taassist/logic/parser/SessionCommandParser.java
  src/main/java/seedu/taassist/model/Model.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/java/seedu/taassist/model/TaAssist.java
  src/test/java/seedu/taassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taassist/logic/commands/SessionCommandTest.java
  src/test/java/seedu/taassist/logic/parser/SessionCommandParserTest.java
  src/test/java/seedu/taassist/logic/parser/TaAssistParserTest.java
  src/test/java/seedu/taassist/model/stubs/ModelStub.java
  src/test/java/seedu/taassist/model/stubs/ModelStubNeverInFocusMode.java
Labels: type.Enhancement

#251 Fix styling error in the User Guide.
  docs/UserGuide.md
  docs/team/bubbl3t.md
Labels: type.Bug, documentation, priority.LOW

#252 Update Ui related documentation and code
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/app-icon.png
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleClassListCard.fxml
Labels: type.Bug, documentation, priority.HIGH

#256 DG: Add details on Querying Session Scores
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ObservableUpdateSequenceDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/ObservableUpdateSequenceDiagram.png
  docs/team/berted.md
Labels: documentation, priority.MEDIUM, type.Chore

#257 UI alignment updates
  src/main/java/seedu/taassist/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleClassListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/fonts/Lato-Bold.ttf
  src/main/resources/view/fonts/Lato-BoldItalic.ttf
  src/main/resources/view/fonts/Lato-Italic.ttf
  src/main/resources/view/fonts/Lato-Regular.ttf
  src/main/resources/view/fonts/Lato-Semibold.ttf
  src/main/resources/view/fonts/Lato-SemiboldItalic.ttf
  src/main/resources/view/fonts/OFL.txt
Labels: type.Bug, enhancement, priority.HIGH

#259 Make student cards collapsible
  src/main/java/seedu/taassist/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
Labels: enhancement

#262 Rename `session` command to `adds`
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddsCommandSequenceDiagram.puml
  docs/images/AddsCommandSequenceDiagram.png
  docs/images/SessionCommandSequenceDiagram.png
  src/main/java/seedu/taassist/logic/commands/AddsCommand.java
  src/main/java/seedu/taassist/logic/commands/ListsCommand.java
  src/main/java/seedu/taassist/logic/parser/AddsCommandParser.java
  src/main/java/seedu/taassist/logic/parser/TaAssistParser.java
  src/test/java/seedu/taassist/logic/commands/AddsCommandTest.java
  src/test/java/seedu/taassist/logic/parser/AddsCommandParserTest.java
  src/test/java/seedu/taassist/logic/parser/TaAssistParserTest.java
Labels: enhancement

#266 Update ug for screenshots based on new Ui
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/scoresAssignment1Result.PNG
  docs/images/scoresAssignment1Result.png
  src/main/resources/view/HelpWindow.css
Labels: documentation, priority.HIGH

#250 UG: Fix punctuation and grammar and added clarity for commands
  docs/UserGuide.md
  docs/_includes/important.html
  docs/_includes/tip.html
  docs/images/exampleExcelFile.png
  docs/images/sampleFocusedGui.png
  docs/images/sampleGui.png
Labels: documentation

#269 Fix bug: clear command does not exit focus mode
  src/main/java/seedu/taassist/logic/commands/ClearCommand.java
  src/main/java/seedu/taassist/logic/commands/CommandResult.java
  src/main/java/seedu/taassist/logic/commands/GradeCommand.java
  src/main/java/seedu/taassist/model/ModelManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleClassListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/taassist/logic/commands/ClearCommandTest.java
  src/test/java/seedu/taassist/model/ModelManagerTest.java
Labels: type.Bug

#271 Fix bug: deleting focused class does not unfocus
  src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
  src/test/java/seedu/taassist/logic/commands/DeletecCommandTest.java
Labels: type.Bug
